### ISSUE TITLE
Memory leak in irdwt

### ISSUE THREAD

**Issue by kevd42** [ricedsp/rwt#10]
I noticed that there is a memory leak in `irdwt` due to the fact that `x_high` is no deallocated in `irdwt_free`. The fix is simply to add `rwt_free(*x_high);` in `irdwt_free`.
Thanks!

**Comment by kalliste** [comment]
Yup - totally right. Thanks! Can you sign a Rice University Contributor Agreement? We'll need it to include your code. What's your e-mail address?
