### ISSUE TITLE
Error using  mdwt (line 83) You must compile wavelet toolbox before use

### ISSUE THREAD

**Issue by chengerr** [ricedsp/rwt#15]
I run Demos-->CS_1D_Demo.m , But error like this appeared. 
Error  mdwt (line 83)
You must compile wavelet toolbox before use.
Would you please tell me Why ?

**Comment by kalliste** [comment]
Ok I'm just going to take your question at face value and tell you why you must compile Wavelet Toolbox before use. The core of Wavelet Toolbox is written in C code to give you the best performance and to demonstrate how the wavelet transform can be calculated efficiently.

**Comment by kalliste** [comment]
Meanwhile you can find the compile.m script in the bin directory. That will handle the compilation for you.
