### ISSUE TITLE
compiling problem

### ISSUE THREAD

**Issue by omarfahmy** [ricedsp/rwt#3]
Hi,
i downloaded this package and i would like to use the function mdwt and midwt in matlab r2013a (x 64 bit) on Windows x64 bit.
The problem that i tried to compile it using mex command that is "mex mdwt.x" but it gives me an error " Creating library C:\Users\OMARFA~1\AppData\Local\Temp\mex_xYdvBV\templib.x and object C:\Users\OMARFA~1\AppData\Local\Temp\mex_xYdvBV\templib.exp 
midwt.obj : error LNK2019: unresolved external symbol idwt referenced in function mexFunction 
midwt.obj : error LNK2019: unresolved external symbol rwt_matlab_init referenced in function mexFunction 
midwt.mexw64 : fatal error LNK1120: 2 unresolved externals 

  C:\PROGRA~1\MATLAB\R2013A\BIN\MEX.PL: Error: Link of 'midwt.mexw64' failed"
So, could you help me please to compile it successfully.

**Comment by kalliste** [comment]
I believe this should be fixed as of commit 7445141086abcdc0ad190b38f700fcb70017d8ee
